[package]
name = "key_character_scan_genome"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
glob = "0.3"

[lib]
name = "key_character_scan_genome"
path = "lib/lib.rs"
